#!/usr/bin/env python3
"""Generate a simple markdown catalog of all skills."""

from __future__ import annotations

import re
from pathlib import Path

import yaml


def extract_frontmatter(text: str) -> dict | None:
    if not text.startswith("---"):
        return None
    parts = text.split("---", 2)
    if len(parts) < 3:
        return None
    try:
        return yaml.safe_load(parts[1]) or {}
    except Exception:
        return None


def find_skill_dirs(root: Path) -> list[Path]:
    candidates = []
    for base in [root / "skills", root]:
        if not base.exists():
            continue
        for p in base.iterdir():
            if p.is_dir() and (p / "SKILL.md").exists():
                candidates.append(p)
    return sorted(set(candidates), key=lambda p: p.name)


def main() -> None:
    root = Path(".").resolve()
    skills = find_skill_dirs(root)

    print("# Skills Catalog\n")
    print(f"Generated from {len(skills)} skill(s).\n")
    print("| Skill | Version | Status | Description |")
    print("|-------|---------|--------|-------------|")

    for skill_dir in skills:
        content = (skill_dir / "SKILL.md").read_text(encoding="utf-8")
        fm = extract_frontmatter(content) or {}
        name = fm.get("name", skill_dir.name)
        meta = fm.get("metadata") or {}
        version = meta.get("version", "—") if isinstance(meta, dict) else "—"
        status = meta.get("status", "—") if isinstance(meta, dict) else "—"
        desc = (fm.get("description") or "")[:120].replace("|", "\\|")
        if len(fm.get("description") or "") > 120:
            desc += "…"
        print(f"| `{name}` | {version} | {status} | {desc} |")

    print("\n---\n*Auto-generated by skills CI*")


if __name__ == "__main__":
    main()